### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by dsantiago** [asanakoy/kaggle-lyft-motion-prediction-av#1]
Dude you should consider creating some course of your on CV field after the end of your Phd. I would gladly pay for it. There's many ppl that know  well the subject but few willing to teach the intrinsics...

**Comment by asanakoy** [comment]
Hey @dsantiago,

Thank you for the kind words! I'm moving in that direction. I have recently started a youtube channel where I explain CV papers every week https://www.youtube.com/channel/UC1iTgaC4cvfIx1k27TFSfug .
Would be glad to see you there. Feel free to leave any comments or questions under my videos - I will definitely reply.

I'm also running a telegram channel, where I regularly post on AI and CV https://t.me/gradientdude.

**Comment by dsantiago** [comment]
Great to know @asanakoy, the Youtube video i already found out and will surely add Telegram... But i still think people like you could make something bigger and have profit in it, as learning is an empirical thing and, in my case, i am a self learner, is really hard to fill some of the gaps...

The way you approached the problem of Lyft competition, with a base CNN, checking centroid with K-Means, Applying Transformers, etc... There's so much involved and i really don't know where all that intuition came from...  Maybe something in this direction would interest many ppl like me in the middle of the knowledge in the area... 

We are already saturated with the many cnn, nlp, etc courses that don't give this kind of intuition.
Thanks for listening...
